### ISSUE TITLE
ExpiredTokenException: The security token included in the request is expired

### ISSUE THREAD

**Issue by olgabot** [grailbio/reflow#98]
Hello! I'm trying to run a small batch and am getting a security token error. I have tried:

- deleting `~/.reflow/reflow.pem`
- Re-creating my AWS_SESSION_TOKEN with 
    ```
    export AWS_SESSION_TOKEN=$(python -c 'import boto3; print(boto3.session.Session().get_credentials().token)')
    ```

### Runbatch config

Here's the config.json and samples.csv:

```
➜  minirun git:(master) ✗ cat config.json
{"program": "/home/ubuntu/reflow-workflows/workflows/rnaseq.rf",
 "runs_file": "/home/ubuntu/reflow-batches/rnaseq/mus/20181030_FS10000331_12_BNT40322-1214/minirun/samples.csv"}
➜  minirun git:(master) ✗ cat samples.csv
id,read1,read2,name,genome,output,region
OPS016_mBAL_RNA_229_L9_S132,s3://czb-seqbot/fastqs/20181030_FS10000331_12_BNT40322-1214/OPS016_mBAL_RNA_229_L9_S132_R1_001.fastq.gz,s3://czb-seqbot/fastqs/20181030_FS10000331_12_BNT40322-1214/OPS016_mBAL_RNA_229_L9_S132_R2_001.fastq.gz,OPS016_mBAL_RNA_229_L9_S132,mouse/vM19,s3://olgabot-maca/aguamenti-test/,west
OPS016_mBAL_RNA_232_N9_S140,s3://czb-seqbot/fastqs/20181030_FS10000331_12_BNT40322-1214/OPS016_mBAL_RNA_232_N9_S140_R1_001.fastq.gz,s3://czb-seqbot/fastqs/20181030_FS10000331_12_BNT40322-1214/OPS016_mBAL_RNA_232_N9_S140_R2_001.fastq.gz,OPS016_mBAL_RNA_232_N9_S140,mouse/vM19,s3://olgabot-maca/aguamenti-test/,west
```

### Runbatch output

```
➜  minirun git:(master) ✗ reflow runbatch -retry
reflow: batch program /home/ubuntu/reflow-workflows/workflows/rnaseq.rf runsfile /home/ubuntu/reflow-batches/rnaseq/mus/20181030_FS10000331_12_BNT40322-1214/minirun/samples.csv
reflow: ec2cluster: instance launch error: ExpiredTokenException: The security token included in the request is expired
        status code: 400, request id: 072771c6-022d-11e9-8d2f-8bcd100f30fa
reflow: ec2cluster: error while launching instance: ExpiredTokenException: The security token included in the request is expired
... more of the same ...
```

### Reflow config

Here's my `reflow config`:

```
➜  minirun git:(master) ✗ reflow config
cluster: ec2cluster
ec2cluster:
  ami: ami-4296ec3a
  cloudconfig: {}
  diskslices: 0
  diskspace: 250
  disktype: gp2
  instancetypes:
  - c1.medium
  - c1.xlarge
  - c3.2xlarge
  - c3.4xlarge
  - c3.8xlarge
  - c3.large
  - c3.xlarge
  - c4.2xlarge
  - c4.4xlarge
  - c4.8xlarge
  - c4.large
  - c4.xlarge
  - c5.large
  - c5.xlarge
  - c5.2xlarge
  - c5.4xlarge
  - c5.9xlarge
  - c5.18xlarge
  - cc2.8xlarge
  - m1.large
  - m1.medium
  - m1.small
  - m1.xlarge
  - m2.2xlarge
  - m2.4xlarge
  - m2.xlarge
  - m3.2xlarge
  - m3.large
  - m3.medium
  - m3.xlarge
  - m4.16xlarge
  - m4.4xlarge
  - m4.xlarge
  - r4.xlarge
  - t1.micro
  - t2.large
  - t2.medium
  - t2.micro
  - t2.nano
  - t2.small
  keyname: ""
  maxinstances: 10
  region: us-west-2
  securitygroup: sg-661d7f19
  sshkey: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0vkJqUtvlKZT3abRllnIFDRq2y3QIqPrDtqJwoZUn8By/QeUpZsJ2gLO/SaikpbGHycJN+87KuBfhbgeFNS81s25A2DohX1ANS9mCSh20fha6PSUZNNX5Qg/em0/fkSQJN+GK1gCrAcLzwKTLJI6ETrgGhpK6e5IS+Stk4ZXtXH+Mjqnu/7LAszLsbjlhJhW6c0B+upjjv4YAfMNDFNs8fEgYKLyyc2GlK7PC9EP0rrBJKMfPQ3PohpRHuUYnPNtpDSFHBgXb6MDKnWA1tQIPe5yKluFri5tbNOLDqUd5229VghQXGon5I7ZVst49mYcZom+HGqJ2bY8qU1sm7tSR ubuntu@ip-172-31-26-220
https: httpsca,/home/ubuntu/.reflow/reflow.pem
repository: s3,czbiohub-reflow-quickstart-cache
```
